### PR TITLE
Fix close problem on Webrick & speed up

### PR DESCRIPTION
**Pull request by odarriba**
Using rails 3.2.14 and Webrick in development stage, the web server can't close because the call to `exit` in the catching of signals fire an exception on Webrick's code.

Now the close of the connection to Serial port is made in an `at_exit` block as described here:
http://www.bigfastblog.com/ruby-exit-exit-systemexit-and-at_exit-blunder

Also, I've reduced sleep times, so the connection is faster.

### CODE REVIEW

**Comment by shokai** [comment]
Hi odarriba thank you for pull request.

I'll use that  you suggested `at_exit`.
But I could not merge your speedup code because those sleep are necessary to support old arduino series.

**Comment by odarriba** [comment]
Do you want to receive a new merge? I can make the changes only to `at_exit` code.

What do you think about using another internal parameter to switch between fast and slow mode? It's because the gem takes too long to connect to Arduino even if the Arduino is newer.
If you like the idea, I can do the changes too :)

**Comment by odarriba** [comment]
I have only one thing to say: Thanks, your gem solves me a huge problem of implementation

**Comment by shokai** [comment]
I'm trying to detect old arduino from USB device-name.

### Debian Linux(raspberry pi)
- /dev/ttyACM0 -> Leonard, Micro, UNO
- /dev/ttyUSB0 -> Decimilla, Duemillanove

### Mac OSX
- /dev/tty.usbmodem1234 -> Leonard, Micro, UNO
- /dev/tty.usbserial-A1234 -> Decimilla, Duemillanove

If the name matches `/(usbmodem|ACM)/` they don't need sleep.

**Comment by odarriba** [comment]
Ok, I'm going to work on it now, and do a new merge request

**Comment by shokai** [comment]
I've push v0.3.2 to rubygems.org.
Thanks a lot of suggestions @odarriba

**Pull request closed without merging**
